name: Generate Metrics
on:
  schedule: [{cron: '0 5,21 * * *'}]
  workflow_dispatch:
    # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    name: Get Latest README Metrics
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Compile Metrics
        if: ${{ success() || failure() }}
        uses: daoxve/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Lagos
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, tex, makefile, qmake, lex, cmake
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: recently-used
          plugin_languages_threshold: 0%
